spring:
  application:
    name: nafull
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
discord:
  token: ${DISCORD_TOKEN}
  guild-id: 807772766979620864
user:
  default:
    id: ${DEFAULT_USER_ID}
    discord-id: ${DEFAULT_USER_DISCORD_ID}
    nickname: ${DEFAULT_USER_NICKNAME}
    password: ${DEFAULT_USER_PASSWORD}
letter:
  base-uri: https://nafull-client.vercel.app/register